name=Array
version=1.4.0
author=Peter Polidoro <peter@polidoro.io>
maintainer=Peter Polidoro <peter@polidoro.io>
sentence=Header-only fixed-capacity array-like container with vector-style size management.
paragraph=Avoids dynamic allocation by storing elements internally in static storage with a variable logical size in a header-only package.
category=Data Storage
url=https://github.com/janelia-arduino/Array
architectures=*
